# baseURL: https://example.com/
languageCode: en-us
title: La·Z
theme: hugo-theme-blueberry-detox
params:
  twitter_name: dacort
  description: "macOS menubar app that opens Zoom meetings in a single click"
  title: La·Z Click
  images:
    - "images/calendar.png"
